### PR TITLE
Reintroduce the 'at least two independent implementations' SHOULD from the previous version of the charter.

### PR DESCRIPTION
**Pull request by hober**
@dwsinger, @gkatsev, @nigelmegitt, and I had a call earlier today to talk about possible ways to resolve Apple's charter FO. One possibility is a "belt-and-suspenders" approach where we have the old charter language as well as the new charter language re: implementations.

This is an inelegant first pass at this. I made no attempt to fiddle with the surrounding wording or to make the resulting frankensteinian text cohere. This PR merely reintroduces the old text as a starting point for conversation.

***
<a href="https://pr-preview.s3.amazonaws.com/hober/charter-timed-text/pull/81.html" title="Last updated on Sep 23, 2022, 9:26 PM UTC (116dc6c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/charter-timed-text/81/229fd25...hober:116dc6c.html" title="Last updated on Sep 23, 2022, 9:26 PM UTC (116dc6c)">Diff</a>

### CODE REVIEW

**Review by dwsinger — APPROVED** [review]

**Comment by nigelmegitt** [comment]
Discussed on [TTWG call today](https://www.w3.org/2022/05/12-tt-minutes.html). Group did not want to approve/accept this change immediately, but preferred to give it more consideration and also see if other alternative resolutions are suggested.

**Comment by nigelmegitt** [comment]
@hober the other open PRs have now been merged - it would be helpful from a preview perspective if you could rebase this change, please.

**Comment by hober** [comment]
> @hober the other open PRs have now been merged - it would be helpful from a preview perspective if you could rebase this change, please.

Done!

**Comment by palemieux** [comment]
What does "implementation" means in this context? For example, what does "implementation" refer to if a specification defines multiple conformance classes, implicitly or explicitly: document, creator, validator and renderer?

**Comment by dwsinger** [comment]
> What does "implementation" means in this context? For example, what does "implementation" refer to if a specification defines multiple conformance classes, implicitly or explicitly: document, creator, validator and renderer?

I think that maybe the point is that it has the same ambiguity as previously-approved charters, and does _not_ answer that question any more than we used to.

**Comment by palemieux** [comment]
> I think that maybe the point is that it has the same ambiguity as previously-approved charters, and does not answer that question any more than we used to.

As a contributor and implementer, and because this has risen to the level of formal objection, I would like to know -- otherwise how is one expected to plan work. I expect others wish to know as well.

**Comment by cconcolato** [comment]
The first sentence of section 3 says:
> In order to advance to [Proposed Recommendation ](https://www.w3.org/Consortium/Process/#RecsPR), each normative feature is expected to meet the requirements set out in [§3.1 ](https://pr-preview.s3.amazonaws.com/w3c/charter-timed-text/81/229fd25...hober:116dc6c.html#advancement)to demonstrate adequate [implementation experience ](https://www.w3.org/Consortium/Process/#implementation-experience).

Your PR adds:
> In order to advance to [Proposed Recommendation](https://www.w3.org/Consortium/Process/#RecsPR), each Recommendation-track Technical Report SHOULD have [at least two independent implementations](https://www.w3.org/Consortium/Process/#implementation-experience) of each feature defined in the Technical Report.

The sentences are very similar. It seems that whatever decision is taken, only one of the 2 sentences should be kept.

**Comment by nigelmegitt** [comment]
> It seems that whatever decision is taken, only one of the 2 sentences should be kept.

Indeed. One of the reasons TTWG was ambivalent about accepting this change was due to the clunkiness of the resulting language.

In terms of decision, my understanding is that this is now going through the FO Council experiment, so unless we resolve the FO some other way (which is not going to be this PR, as it stands now) then the FO Council will be making that decision.

**Review by nigelmegitt — CHANGES_REQUESTED** [review]
No consensus to adopt this within TTWG, putting a Request changes review in to block merge pending FO Council.

**Comment by nigelmegitt** [comment]
Closing this since we now have a proposal from the FO Council at #84 .

**Pull request closed without merging**
